// sampleData.js

export const Samplepayments = [
  {
    id: 1,
    lecturer: "John Doe",
    course: "Mathematics",
    amount: 5000,
  },
  {
    id: 2,
    lecturer: "Jane Smith",
    course: "Physics",
    amount: 4500,
  },
  {
    id: 3,
    lecturer: "Michael Johnson",
    course: "Chemistry",
    amount: 5200,
  },
  {
    id: 4,
    lecturer: "John Doe",
    course: "Mathematics",
    amount: 6000,
  },
  {
    id: 5,
    lecturer: "Jane Smith",
    course: "Biology",
    amount: 4000,
  },
  {
    id: 6,
    lecturer: "Michael Johnson",
    course: "Mathematics",
    amount: 5500,
  },
  {
    id: 7,
    lecturer: "John Doe",
    course: "Physics",
    amount: 4800,
  },
  {
    id: 8,
    lecturer: "Jane Smith",
    course: "Chemistry",
    amount: 5200,
  },
  {
    id: 9,
    lecturer: "Michael Johnson",
    course: "Biology",
    amount: 4300,
  },
  {
    id: 10,
    lecturer: "John Doe",
    course: "Mathematics",
    amount: 5000,
  },
  {
    id: 11,
    lecturer: "John Doe",
    course: "Mathematics",
    amount: 5200,
  },
  {
    id: 12,
    lecturer: "Jane Smith",
    course: "Physics",
    amount: 4500,
  },
  {
    id: 13,
    lecturer: "Michael Johnson",
    course: "Chemistry",
    amount: 5000,
  },
  {
    id: 14,
    lecturer: "John Doe",
    course: "Physics",
    amount: 4700,
  },
  {
    id: 15,
    lecturer: "Jane Smith",
    course: "Biology",
    amount: 4100,
  },
  {
    id: 16,
    lecturer: "Michael Johnson",
    course: "Mathematics",
    amount: 5500,
  },
  {
    id: 17,
    lecturer: "John Doe",
    course: "Mathematics",
    amount: 5800,
  },
  {
    id: 18,
    lecturer: "Jane Smith",
    course: "Chemistry",
    amount: 5100,
  },
  {
    id: 19,
    lecturer: "Michael Johnson",
    course: "Biology",
    amount: 4300,
  },
  {
    id: 20,
    lecturer: "John Doe",
    course: "Mathematics",
    amount: 4900,
  },
  {
    id: 21,
    lecturer: "John Doe",
    course: "Physics",
    amount: 4600,
  },
  {
    id: 22,
    lecturer: "Jane Smith",
    course: "Physics",
    amount: 4400,
  },
  {
    id: 23,
    lecturer: "Michael Johnson",
    course: "Chemistry",
    amount: 5000,
  },
  {
    id: 24,
    lecturer: "John Doe",
    course: "Physics",
    amount: 4700,
  },
  {
    id: 25,
    lecturer: "Jane Smith",
    course: "Biology",
    amount: 4000,
  },
  {
    id: 26,
    lecturer: "Michael Johnson",
    course: "Mathematics",
    amount: 5600,
  },
  {
    id: 27,
    lecturer: "John Doe",
    course: "Mathematics",
    amount: 5000,
  },
  {
    id: 28,
    lecturer: "Jane Smith",
    course: "Chemistry",
    amount: 5300,
  },
  {
    id: 29,
    lecturer: "Michael Johnson",
    course: "Biology",
    amount: 4200,
  },
  {
    id: 30,
    lecturer: "John Doe",
    course: "Mathematics",
    amount: 5000,
  },
  {
    id: 31,
    lecturer: "John Doe",
    course: "Mathematics",
    amount: 5500,
  },
  {
    id: 32,
    lecturer: "Jane Smith",
    course: "Physics",
    amount: 4600,
  },
  {
    id: 33,
    lecturer: "Michael Johnson",
    course: "Chemistry",
    amount: 5100,
  },
  {
    id: 34,
    lecturer: "John Doe",
    course: "Physics",
    amount: 4800,
  },
  {
    id: 35,
    lecturer: "Jane Smith",
    course: "Biology",
    amount: 4100,
  },
  {
    id: 36,
    lecturer: "Michael Johnson",
    course: "Mathematics",
    amount: 5700,
  },
  {
    id: 37,
    lecturer: "John Doe",
    course: "Mathematics",
    amount: 5900,
  },
  {
    id: 38,
    lecturer: "Jane Smith",
    course: "Chemistry",
    amount: 5400,
  },
  {
    id: 39,
    lecturer: "Michael Johnson",
    course: "Biology",
    amount: 4300,
  },
  {
    id: 40,
    lecturer: "John Doe",
    course: "Mathematics",
    amount: 4900,
  },
  {
    id: 41,
    lecturer: "John Doe",
    course: "Physics",
    amount: 4600,
  },
  {
    id: 42,
    lecturer: "Jane Smith",
    course: "Physics",
    amount: 4500,
  },
  {
    id: 43,
    lecturer: "Michael Johnson",
    course: "Chemistry",
    amount: 5200,
  },
  {
    id: 44,
    lecturer: "John Doe",
    course: "Physics",
    amount: 4800,
  },
  {
    id: 45,
    lecturer: "Jane Smith",
    course: "Biology",
    amount: 4000,
  },
  {
    id: 46,
    lecturer: "Michael Johnson",
    course: "Mathematics",
    amount: 5600,
  },
  {
    id: 47,
    lecturer: "John Doe",
    course: "Mathematics",
    amount: 5000,
  },
  {
    id: 48,
    lecturer: "Jane Smith",
    course: "Chemistry",
    amount: 5300,
  },
  {
    id: 49,
    lecturer: "Michael Johnson",
    course: "Biology",
    amount: 4200,
  },
  {
    id: 50,
    lecturer: "John Doe",
    course: "Mathematics",
    amount: 5000,
  },
];
